version: '3'

services:
  reactapp:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: reactapp
    stdin_open: true
    volumes:
       - .:/app
       - /app/node_modules